# Generated by Django 3.2 on 2022-08-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_recipe_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_title',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to=''),
        ),
    ]
