# Generated by Django 3.2 on 2022-08-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220817_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
